dist: xenial
sudo: required

language: clojure

before_script:
  - ./bin/ci/install_on_debian.sh
  - until sudo lsof -i:5672; do echo "Waiting for RabbitMQ to start..."; sleep 1; done
  - ./bin/ci/before_script.sh

script: lein all test

jdk:
  - oraclejdk8
services:
  - rabbitmq
notifications:
  recipients:
    - michael@rabbitmq.com
